### ISSUE TITLE
Fail to fix broken database

### ISSUE THREAD

**Issue by tsuchm** [clear-code/redmine_full_text_search#73]
I have just tried to a procedure to fix a broken database.   However, the step to re-create the database schema complains as follows:

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=full_text_search VERSION=0
Migrating full_text_search (Full Text Search plugin)...
== 20170810052427 AddIndexToIssueContents: reverting ==========================
-- remove_index(:issue_contents, :contents)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine.issue_contents' doesn't exist: SHOW KEYS FROM `issue_contents`
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:448:in `indexes'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:637:in `index_name_exists?'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:993:in `index_name_for_remove'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:593:in `remove_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:31:in `block (2 levels) in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:515:in `down'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:30:in `block in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:547:in `block in reversible'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:746:in `execute_block'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:499:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:606:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:830:in `down'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:805:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:453:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:464:in `migrate'
/var/lib/redmine-3.4.10/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redmine.issue_contents' doesn't exist: SHOW KEYS FROM `issue_contents`
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:448:in `indexes'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:637:in `index_name_exists?'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:993:in `index_name_for_remove'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:593:in `remove_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:31:in `block (2 levels) in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:515:in `down'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:30:in `block in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:547:in `block in reversible'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:746:in `execute_block'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:499:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:606:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:830:in `down'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:805:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:453:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:464:in `migrate'
/var/lib/redmine-3.4.10/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Table 'redmine.issue_contents' doesn't exist
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:448:in `indexes'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:637:in `index_name_exists?'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:993:in `index_name_for_remove'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:593:in `remove_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:31:in `block (2 levels) in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:515:in `down'
/var/lib/redmine-3.4.10/plugins/full_text_search/db/migrate/20170810052427_add_index_to_issue_contents.rb:30:in `block in change'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:547:in `block in reversible'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:746:in `execute_block'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:499:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:498:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:606:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:830:in `down'
/var/lib/gems/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:805:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:453:in `migrate'
/var/lib/redmine-3.4.10/lib/redmine/plugin.rb:464:in `migrate'
/var/lib/redmine-3.4.10/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

What should I do?

**Comment by kou** [comment]
It has been fixed on master.
You can use master when we upgrade your Redmine to 4.0.

**Comment by tsuchm** [comment]
Following your comment, I tried the master on Redmine 4.0.5.  However, I still faced the following error message.

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=full_text_search VERSION=0
(in /var/lib/redmine-4.0.5)
== 20190226093843 AddMissingIndexesToSearcherRecords: reverting ===============
== 20190226093843 AddMissingIndexesToSearcherRecords: reverted (0.0016s) ======

== 20190226093842 ExtendContentSize: reverting ================================
== 20190226093842 ExtendContentSize: reverted (0.0000s) =======================

== 20170810052427 AddIndexToIssueContents: reverting ==========================
== 20170810052427 AddIndexToIssueContents: reverted (0.0000s) =================

== 20170810045914 CreateIssueContents: reverting ==============================
-- drop_table(:issue_contents, {:options=>"ENGINE=Mroonga", :id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Unknown table 'redmine.issue_contents': DROP TABLE `issue_contents`
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:340:in `drop_table'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:687:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:812:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:514:in `down'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1015:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:536:in `migrate_plugin'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:477:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:488:in `migrate'
/var/lib/redmine-4.0.5/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'redmine.issue_contents': DROP TABLE `issue_contents`
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:340:in `drop_table'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:687:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:812:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:514:in `down'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1015:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:536:in `migrate_plugin'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:477:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:488:in `migrate'
/var/lib/redmine-4.0.5/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Unknown table 'redmine.issue_contents'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:340:in `drop_table'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:687:in `block in revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `revert'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:812:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:514:in `down'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1015:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:536:in `migrate_plugin'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:477:in `migrate'
/var/lib/redmine-4.0.5/lib/redmine/plugin.rb:488:in `migrate'
/var/lib/redmine-4.0.5/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by kou** [comment]
I've added more checks for no table case.
Could you try again with the current master?

**Comment by tsuchm** [comment]
Thanks a lot.
